/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package esprit.rt.gui;

import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserAdapter;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserNavigationEvent;
import esprit.rt.dao.ClientDAO;
import esprit.rt.dao.RestaurateurDAO;
import esprit.rt.utilities.FontsPartieRestaurateur;
import esprit.rt.utilities.GraphReaderExample;
import esprit.rt.utilities.SessionRestoTunisie;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.parser.ParserDelegator;

/**
 *
 * @author Aditsan Kadmus
 */
public class AuthentificationClientRest extends javax.swing.JFrame {

    /**
     * Creates new form AuthentificationClientRest
     */
    Font fTitle, fLbl, fBtn;
    List<JLabel> jlt;
    List<JLabel> jbtnl;
    private boolean client;
    RestaurateurDAO udao = new RestaurateurDAO();
    ClientDAO cdao = new ClientDAO();
    
    
    
public static String API_KEY = "243838029135919";
public static String SECRET = "bf25756de67cd76bd47323bee076414c";
public static String nom="";
public static String firstRequest = "https://graph.facebook.com/oauth/authorize?"
+ "client_id="
+ API_KEY
+ "&redirect_uri=http://www.facebook.com/connect/login_success.html&"
+ "scope=publish_stream,offline_access,create_event,read_stream,email,user_birthday";

public static String secondRequest="https://graph.facebook.com/oauth/access_token?"
+ "client_id="
+ API_KEY
+ "&redirect_uri=http://www.facebook.com/connect/login_success.html&"
+ "client_secret=" + SECRET + "&code=";

public static String access_token = "";
public static boolean firstRequestDone = false;
public static boolean secondRequestDone = false;
    
    
    
    public AuthentificationClientRest() throws FontFormatException, IOException {
        SessionRestoTunisie.auth = this;
        client=true;
        jlt = new ArrayList<JLabel>();
        jbtnl = new ArrayList<JLabel>();
        fBtn = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/esprit/rt/fonts/franchise_bold.ttf"));
        fTitle = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/esprit/rt/fonts/track.ttf"));
        fLbl = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/esprit/rt/fonts/onramp.ttf"));
        initComponents();
        jbtnl.add(btnRest);
        jlt.add(labelPassword);
        jlt.add(labelEmail);
        jbtnl.add(btnClient);
        jbtnl.add(btnRest);
        for (JLabel jl : jlt)
        {
            jl.setFont(fLbl);
            jl.setFont(fLbl.deriveFont(0,50));
        }
        for (JLabel jl : jbtnl)
        {
            jl.setFont(fBtn);
            jl.setFont(fBtn.deriveFont(0,50));
        }
        jPasswordField1.setFont(new FontsPartieRestaurateur().getFont(FontsPartieRestaurateur.TXTFIELD, 40f));
        jTextField2.setFont(new FontsPartieRestaurateur().getFont(FontsPartieRestaurateur.TXTFIELD, 40f));
        setLocationRelativeTo(null);
    }

    public boolean isClient() {
        return client;
    }

    public void setClient(boolean client) {
        this.client = client;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jClient = new javax.swing.JPanel();
        btnClient = new javax.swing.JLabel();
        jRestaurateur = new javax.swing.JPanel();
        btnRest = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnEntrer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnFb = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnQuitter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authentification");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(29, 29, 29));

        jClient.setBackground(new java.awt.Color(29, 29, 29));

        btnClient.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnClient.setForeground(new java.awt.Color(204, 204, 204));
        btnClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/rt/images/user003.png"))); // NOI18N
        btnClient.setText("Client");
        btnClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabMouseOver(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabMouseOut(evt);
            }
        });

        javax.swing.GroupLayout jClientLayout = new javax.swing.GroupLayout(jClient);
        jClient.setLayout(jClientLayout);
        jClientLayout.setHorizontalGroup(
            jClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnClient)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jClientLayout.setVerticalGroup(
            jClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRestaurateur.setBackground(new java.awt.Color(204, 204, 204));

        btnRest.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/rt/images/restaurateur002.png"))); // NOI18N
        btnRest.setText("Restaurateur");
        btnRest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabMouseOver(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabMouseOut(evt);
            }
        });

        javax.swing.GroupLayout jRestaurateurLayout = new javax.swing.GroupLayout(jRestaurateur);
        jRestaurateur.setLayout(jRestaurateurLayout);
        jRestaurateurLayout.setHorizontalGroup(
            jRestaurateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRestaurateurLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(btnRest)
                .addGap(111, 111, 111))
        );
        jRestaurateurLayout.setVerticalGroup(
            jRestaurateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRestaurateurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRest)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnEntrer.setBackground(new java.awt.Color(29, 29, 29));
        btnEntrer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/rt/images/enter001.png"))); // NOI18N
        jLabel1.setText("S'authentifier");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickAuth(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEntrerLayout = new javax.swing.GroupLayout(btnEntrer);
        btnEntrer.setLayout(btnEntrerLayout);
        btnEntrerLayout.setHorizontalGroup(
            btnEntrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEntrerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnEntrerLayout.setVerticalGroup(
            btnEntrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEntrerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btnFb.setBackground(new java.awt.Color(29, 29, 29));
        btnFb.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/rt/images/fb001.png"))); // NOI18N
        jLabel2.setText("Se connecter avec votre compte Facebook");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnFbLayout = new javax.swing.GroupLayout(btnFb);
        btnFb.setLayout(btnFbLayout);
        btnFbLayout.setHorizontalGroup(
            btnFbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnFbLayout.setVerticalGroup(
            btnFbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFbLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32))
        );

        btnQuitter.setBackground(new java.awt.Color(29, 29, 29));
        btnQuitter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/rt/images/exit003.png"))); // NOI18N
        jLabel3.setText("Quitter");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnQuitterLayout = new javax.swing.GroupLayout(btnQuitter);
        btnQuitter.setLayout(btnQuitterLayout);
        btnQuitterLayout.setHorizontalGroup(
            btnQuitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQuitterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnQuitterLayout.setVerticalGroup(
            btnQuitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQuitterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelEmail.setForeground(new java.awt.Color(204, 204, 204));
        labelEmail.setText("Email");

        labelPassword.setForeground(new java.awt.Color(204, 204, 204));
        labelPassword.setText("Mot de passe");

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEntrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRestaurateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jRestaurateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnEntrer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void tabClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClicked
        jTextField2.setText("");
        jPasswordField1.setText("");
        if (this.isClient())
        {
            jRestaurateur.setBackground(Color.decode("#1d1d1d"));
            jClient.setBackground(Color.decode("#cccccc"));
            btnRest.setForeground(Color.decode("#cccccc"));
            btnClient.setForeground(Color.decode("#1d1d1d"));
            btnClient.setIcon(new ImageIcon(this.getClass().getResource("/esprit/rt/images/user002.png")));
            btnRest.setIcon(new ImageIcon(this.getClass().getResource("/esprit/rt/images/restaurateur003.png")));
            btnFb.setVisible(false);
            this.setClient(false);
        }
        else
        {
            jRestaurateur.setBackground(Color.decode("#cccccc"));
            jClient.setBackground(Color.decode("#1d1d1d"));
            btnRest.setForeground(Color.decode("#1d1d1d"));
            btnClient.setForeground(Color.decode("#cccccc"));
            btnClient.setIcon(new ImageIcon(this.getClass().getResource("/esprit/rt/images/user003.png")));
            btnRest.setIcon(new ImageIcon(this.getClass().getResource("/esprit/rt/images/restaurateur002.png")));
            btnFb.setVisible(true);
            this.setClient(true);
        }
    }//GEN-LAST:event_tabClicked

    private void tabMouseOver(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseOver
        if (evt.getComponent().equals(btnClient))
        {
            if (!isClient())
            {
                this.setCursor (Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                evt.getComponent().setForeground(Color.decode("#4c4c4c"));
            }
        }
        if (evt.getComponent().equals(btnRest))
        {
            if (isClient())
            {
                this.setCursor (Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                evt.getComponent().setForeground(Color.decode("#4c4c4c"));
            }
        }
        
    }//GEN-LAST:event_tabMouseOver

    private void tabMouseOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseOut
        this.setCursor (Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        if (evt.getComponent().equals(btnClient))
        {
            if (!isClient())
            {
                evt.getComponent().setForeground(Color.decode("#1d1d1d"));
            }
        }
        if (evt.getComponent().equals(btnRest))
        {
            if (isClient())
            {
                evt.getComponent().setForeground(Color.decode("#1d1d1d"));
            }
        }
    }//GEN-LAST:event_tabMouseOut

    private void clickAuth(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickAuth
        // TODO add your handling code here:
        
        if (jTextField2.getText().trim().equals(""))
        {
            new FlatosDialogos(this,"Le champs email est vide",30f,false).setVisible(true);
            return;
        }
        if ( new String(jPasswordField1.getPassword()).trim().equals(""))
        {
            new FlatosDialogos(this,"Le champs mot de passe est vide",30f,false).setVisible(true);
            return;
        }
        String[] a = {jTextField2.getText(), new String(jPasswordField1.getPassword())}; 
        int res = -1;
        if (client)
        {
            System.out.println("***");
            res = new ClientDAO().auth(a);
        }
        if (!client)
        {res = new RestaurateurDAO().auth(a);}
        if ( res != -1 )
        {
            SessionRestoTunisie.setId(res);
            try {
                if (!client)
                {new RestaurateurMainMenu().setVisible(true);}
                else
                {
                    System.out.println("***");
                    new MenuConsultationRestaurant().setVisible(true);}
            } catch (FontFormatException ex) {
                Logger.getLogger(AuthentificationClientRest.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(AuthentificationClientRest.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
        if ( res == -1 )
        {
            jPasswordField1.setText("");
            new FlatosDialogos(this,"Votre email ou mot de passe est incorrect!",30f,false).setVisible(true);
            
        }
    }//GEN-LAST:event_clickAuth

    private void btnsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsMouseEntered
       this.setCursor (Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
       evt.getComponent().getParent().setBackground(Color.decode("#818181"));
    }//GEN-LAST:event_btnsMouseEntered

    private void btnsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsMouseExited
        this.setCursor (Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        evt.getComponent().getParent().setBackground(Color.decode("#1d1d1d"));
    }//GEN-LAST:event_btnsMouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            new RestaurateurMainMenu();
        } catch (FontFormatException ex) {
            Logger.getLogger(AuthentificationClientRest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AuthentificationClientRest.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable(){
            
            @Override
            public void run() {
                NativeInterface.open();
                NativeInterface.initialize();
               
                final JFrame authFrame = new JFrame();
                // Create the JWebBrowser and add the WebBrowserAdapter
                JPanel webBrowserPanel = new JPanel(new BorderLayout());
                final JWebBrowser webBrowser = new JWebBrowser();

                webBrowser.navigate(firstRequest);
             
               
                webBrowser.addWebBrowserListener(new WebBrowserAdapter() {   

            @Override
            public void locationChanged(WebBrowserNavigationEvent e) {          
                super.locationChanged(e);
                // Check if first request was not done
                if (!firstRequestDone) {
                // Check if you left the location and were redirected to the next 
                // location
                if (e.getNewResourceLocation().contains("http://www.facebook.com/connect/login_success.html?code")){
                // If it successfully redirects you, get the verification code
                // and go for a second request
                String[] splits = e.getNewResourceLocation().split("=");
                String stage2temp = secondRequest + splits[1];
                System.out.println("First ="+splits[1]);
                webBrowser.navigate(stage2temp);
                firstRequestDone = true;
                }

                } 
                else 
                {
                // If secondRequest is not done yet, you perform this and get the 
                // access_token
                if (!secondRequestDone) 
                {
                authFrame.setVisible(false);
                System.out.println(webBrowser.getHTMLContent());
                // Create reader with the html content
                StringReader readerSTR = new StringReader(webBrowser.getHTMLContent());
                // Create a callback for html parser
                HTMLEditorKit.ParserCallback callback = 
                new HTMLEditorKit.ParserCallback() {
                @Override
                public void handleText(char[] data,int pos) {
                System.out.println(data);
                // because there is only one line with the access_token 
                // in the html content you can parse it.
                String string = new String(data);
                String[] temp1 = string.split("&");
                String[] temp2 = temp1[0].split("=");
                System.out.println("access tocken="+temp2);
                access_token = temp2[1];
                new GraphReaderExample(access_token).runEverything();
//                MenuClient client =new MenuClient();
//                client.setVisible(true);
//                AuthentificationClientRest.this.setVisible(false);
                

                    }
                    };
                    try {
                    // Call the parse method 
                    new ParserDelegator().parse(readerSTR,callback,false);
                    } catch (IOException e1) {
                    e1.printStackTrace();
                    }
                    // After everything is done, you can dispose the jframe
                    authFrame.dispose(); 
                    }
                    }
                    }

                    });
                    webBrowserPanel.add(webBrowser,BorderLayout.CENTER);
                    authFrame.add(webBrowserPanel);
                    authFrame.setSize(1200, 750);
                    authFrame.setLocationRelativeTo(null);
                    authFrame.setVisible(true);
                     }
            });
        
        
        
                                         
       
        
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthentificationClientRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthentificationClientRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthentificationClientRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthentificationClientRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AuthentificationClientRest().setVisible(true);
                } catch (FontFormatException ex) {
                    Logger.getLogger(AuthentificationClientRest.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(AuthentificationClientRest.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClient;
    private javax.swing.JPanel btnEntrer;
    private javax.swing.JPanel btnFb;
    private javax.swing.JPanel btnQuitter;
    private javax.swing.JLabel btnRest;
    private javax.swing.JPanel jClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel jRestaurateur;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
